---
# Update with upstream
- name: "Fetch upstream and rebase"
  shell: git checkout gh-pages && git fetch upstream && git rebase upstream/gh-pages
  args:
    chdir: "{{ github_folder }}/documentation-archive"
  ignore_errors: false

- name: "Change version to {{ release_version }}"
  shell: git checkout v{{ release_version }}
  args:
    chdir: "{{ github_folder }}/jhipster.github.io/"

- name: "Build website for archive"
  shell: npm i && SITE_BASE_URL=/documentation-archive/v{{ release_version }}/ IS_DOCS_ARCHIVE=true npm run build
  args:
    chdir: "{{ github_folder }}/jhipster.github.io/"

- name: "Copy the documentation archive"
  shell: cp -R ./build {{ github_folder }}/documentation-archive/v{{ release_version }}
  args:
    chdir: "{{ github_folder }}/jhipster.github.io/"

- name: "Switch back to main branch"
  shell: git checkout main && git checkout -- . && git clean -fd
  args:
    chdir: "{{ github_folder }}/jhipster.github.io/"

- name: "Add version in index.html"
  lineinfile:
    path: "{{ github_folder }}documentation-archive/index.html"
    regexp: "</li></ul>"
    insertbefore: "</li></ul>"
    line: |
      </li><li><a href="v{{ release_version }}/">v{{ release_version }}/</a>
      </li></ul>

- name: "Commit Release {{ release_version }}"
  shell: git add . && git commit -m 'Release v{{ release_version }}'
  args:
    chdir: "{{ github_folder }}/documentation-archive/"
